# Generated by Django 5.0.3 on 2024-03-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('profissional', models.TextField(max_length=255)),
                ('cabelo', models.IntegerField()),
                ('barba', models.IntegerField()),
                ('pagamento', models.DateField()),
            ],
        ),
    ]
