# Generated by Django 5.0.3 on 2024-05-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0002_alter_usuario_nome_alter_usuario_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.TextField(default='', max_length=50),
        ),
    ]
