# Generated by Django 5.0.3 on 2024-05-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0004_alter_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contato',
            field=models.CharField(default='(00) 00000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
